// get all users
# GET http://localhost:3000/auth

// get user by email
# GET http://localhost:3000/auth?email=abc@gmail.com

// get user by id
# GET http://localhost:3000/auth/6

// get currently logged in user
# GET http://localhost:3000/auth/whoami

// signup user
# POST http://localhost:3000/auth/signup
# Content-Type: application/json

# {
#     "email": "test@gmail.com",
#     "password": "12345"
# }

// signin user 
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "12345"
}

// signout user
POST http://localhost:3000/auth/signout

// delete user by id
# DELETE http://localhost:3000/auth/8

# PATCH http://localhost:3000/auth/7
# content-type: application/json

# {
#     "email": "sujay@gmail.com"
# }