// get all users
# GET http://localhost:3000/auth

// get user by email
# GET http://localhost:3000/auth?email=abc@gmail.com

// get user by id
GET http://localhost:3000/auth/6

// create a new user
# POST http://localhost:3000/auth/signup
# Content-Type: application/json

# {
#     "email": "soham@gmail.com",
#     "password": "abc123"
# }

// delete user by id
# DELETE http://localhost:3000/auth/8

# PATCH http://localhost:3000/auth/7
# content-type: application/json

# {
#     "email": "sujay@gmail.com"
# }